# Generated by Django 5.2.12 on 2026-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactado',
            field=models.BooleanField(default=False, verbose_name='¿Se ha contactado al cliente?'),
        ),
    ]
