# Generated by Django 5.2.12 on 2026-03-24 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('content', models.TextField(verbose_name='Contenido del curso')),
                ('author', models.CharField(max_length=100, verbose_name='Docente del curso')),
                ('call_link', models.URLField(verbose_name='Enlace de agendado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el: ')),
            ],
        ),
    ]
