# Generated by Django 5.2.12 on 2026-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en Home'),
        ),
    ]
