# Generated by Django 5.2.12 on 2026-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_course_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='toc',
            field=models.FileField(blank=True, null=True, upload_to='course_toc/', verbose_name='Índice del curso'),
        ),
    ]
