# Generated by Django 5.2.12 on 2026-03-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_course_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='cursos/images/', verbose_name='Imagen del curso'),
        ),
    ]
