# Generated by Django 5.2.12 on 2026-03-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/images/', verbose_name='Imagen del curso'),
        ),
    ]
