# Generated by Django 5.2.12 on 2026-03-30 09:44

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='cursos/images/', verbose_name='Imagen del curso'),
        ),
    ]
