# Generated by Django 5.2.12 on 2026-03-30 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido del curso'),
        ),
    ]
